services:
  mysql:
    container_name: tenon-mysql
    image: 'mysql:8.0.29'
    environment:
      - 'MYSQL_DATABASE=tenon'
      - 'MYSQL_ROOT_PASSWORD=XzHvhX4CDaN696oQAXdmlcsrqgWbkxRl'
      - 'TZ=Asia/Shanghai'
    ports:
      - "3306:3306"
    volumes:
      - "./tenon.sql:/tenon.sql"
      - "mysql8-volume:/etc/mysql/conf.d"
      - "mysql8-volume:/var/lib/mysql"
      - "mysql8-volume:/logs"
    command: ["--default-authentication-plugin=mysql_native_password", "--init-file=/tenon.sql"]
  redis:
    image: 'redis:7.0.8'
    container_name: tenon-redis
    sysctls:
      - net.core.somaxconn=1024
    ports:
      - "6379:6379"
    volumes:
      - "redis-volume:/data"
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass d9d2j9w2 --appendonly yes
    environment:
      - TZ=Asia/Shanghai
volumes:
  mysql8-volume:
  redis-volume:
